apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rcry2eb48-nodejs
  janus-idp.io/tekton: rcry2eb48-nodejs
  backstage.io/kubernetes-id: rcry2eb48-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rcry2eb48-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
